import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AppContextProvider } from "@/context/AppContext.jsx";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AppContextProvider>
        <Navbar/>
        <ToastContainer position="top-right" autoClose={3000} />
        <div className=" md:px-16 lg:px-24 xl:px-32">
        {children}
        </div>
        <Footer/>
        </AppContextProvider>
      </body>
    </html>
  );
}
